# Generated by Django 5.1 on 2024-08-26 23:11

import jsonfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('data_criacao', models.DateField(auto_now_add=True)),
                ('questoes', jsonfield.fields.JSONField()),
                ('time_a_pontos', models.IntegerField(default=0)),
                ('time_b_pontos', models.IntegerField(default=0)),
                ('time_c_pontos', models.IntegerField(default=0)),
                ('time_d_pontos', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Questao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enunciado', models.CharField(max_length=500)),
                ('respostas', jsonfield.fields.JSONField()),
                ('resposta_correta', models.IntegerField()),
            ],
        ),
    ]
