# Generated by Django 5.1 on 2024-08-28 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='questao',
            name='categoria',
            field=models.CharField(default=1, max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='questao',
            name='nivel',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
